// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqBzLFkL_bx3pVHR5F-cNRBYs7gQAtdNA',
    appId: '1:414347331271:web:a48305e18b4b0eefc360e2',
    messagingSenderId: '414347331271',
    projectId: 'sunny-chen-project',
    authDomain: 'sunny-chen-project.firebaseapp.com',
    storageBucket: 'sunny-chen-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABBZqFZk1lF938UR5iO7n2p3mG7VvGxz8',
    appId: '1:414347331271:android:b396a2570fe5399fc360e2',
    messagingSenderId: '414347331271',
    projectId: 'sunny-chen-project',
    storageBucket: 'sunny-chen-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHs8CvJu096C0ea7eIB2OusWq5CCbz4R0',
    appId: '1:414347331271:ios:25024beb526e911ac360e2',
    messagingSenderId: '414347331271',
    projectId: 'sunny-chen-project',
    storageBucket: 'sunny-chen-project.firebasestorage.app',
    iosBundleId: 'com.example.sunnyChenProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHs8CvJu096C0ea7eIB2OusWq5CCbz4R0',
    appId: '1:414347331271:ios:25024beb526e911ac360e2',
    messagingSenderId: '414347331271',
    projectId: 'sunny-chen-project',
    storageBucket: 'sunny-chen-project.firebasestorage.app',
    iosBundleId: 'com.example.sunnyChenProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqBzLFkL_bx3pVHR5F-cNRBYs7gQAtdNA',
    appId: '1:414347331271:web:a1d5d37d5b1dcdd8c360e2',
    messagingSenderId: '414347331271',
    projectId: 'sunny-chen-project',
    authDomain: 'sunny-chen-project.firebaseapp.com',
    storageBucket: 'sunny-chen-project.firebasestorage.app',
  );
}
